/*
    - form of IPC
    - notification to a process indicating occurrence of an event
    - way to communicate information to a process about state of other process, the OS, and hardware.
    - generated by system or user can do it programmatically.
    - when signal sent, OS interrupts process' normal flow to deliver the signal.
        - process has to deal with signal immediately (can ignore)
    - process can recieve signal asynchronously (at any time)
    - fix set of signal - just a short message that contains an integer
        - SIGHUP | 1 | Term | hangup detected on controlling terminal or death of controlling process
        - SIGINT | 2 | Term | interrupt from keyboard (ctrl-c)
        - SIGQUIT | 3 | Core | quit instruction
        - SIGILL | 4 | Core | Illegal instruction
        - SIGABRT | 6 | Core | Abort signal from abort(3)
        - SIGFPE | 8 | Core | Floating point exception
        - SIGKILL | 9 | Term | Kill signal
        - SIGSEGB | 11 | Core | Invalid memory reference
        - SIGKILL | 13 | Term | Broken pipe: write to pipe wiht no readers
        - SIGTSTP (ctrl-z)
        - SIGCONT (fg/bg)
        - SIGTERM terminate program
        - other signal events: illegal instructions, segmentation violations, termination orders, when using fgets()
    - when signal raised, default actions performed. each signal has name, value, default action 
        - Term - process will terminate
        - Core - process will terminate and produce core dump file
        - Ign - process ignores signal
        - Stop - process stops like ctr-z
        - Cont - process will continue from being stopped
*/

/*
raising a signal
    - can be generated using:
        - raise() sends signal to current process
            -int raise(int sig)
                - if successful signal specified in sig is generated
                - if not, raise() returns non-zero value
            - can only send signal to program that contains it
            - cannot send signal to other processes
        - kill() sends signal to specific process



*/


#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

int main(){
    printf("Testing SIGSTOP");
    raise (SIGSTOP);
    return 0;


}